version: '3'
services:

  proxy:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf

  front-end:
    build: ./er-frontend/
    image: s63d/front-end-nginx
    ports:
      - 83:80

  account-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: accounts
      MYSQL_DATABASE: account-db
    volumes: 
      - account-data:/var/lib/mysql
    ports:
      - 3307:3306
  account-service:
    image: com.s63d/er-account-service:6.0.0
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports:
      - 8081:8080

  vehicle-db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: accounts
        MYSQL_DATABASE: vehicle-db
      volumes: 
        - vehicle-data:/var/lib/mysql
      ports:
       - 3308:3306
  vehicle-service:
    image: com.s63d/er-vehicle-service:6.0.0
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports:
      - 8082:8080

  trip-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: accounts
      MYSQL_DATABASE: trip-db
    volumes: 
      - trip-data:/var/lib/mysql
    ports:
      - 3309:3306
  trip-service:
    image: com.s63d/er-trip-service:6.0.0
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports:
      - 8084:8080

  invoice-db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: accounts
        MYSQL_DATABASE: invoice-db
      volumes:
        - invoice-data:/var/lib/mysql
      ports:
        - 3310:3306
  invoice-service:
    image: com.s63d/er-invoice-service:6.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
    ports:
      - 8085:8080
  trip-consumer:
    image: com.s63d/er-trip-consumer:6.0.0
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports: 
      - 8083:8080
  trip-middleware:
    image: com.s63d/trip-middleware:6.0.0
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports: 
      - 8086:8080
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  grafana:
    image: grafana/grafana
    volumes: 
      - grafana-data:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning/
    ports:
      - 3000:3000

volumes:
  account-data:
  vehicle-data:
  trip-data:
  invoice-data:
  prometheus-data:
  grafana-data:
