version: '3'
services:

  account-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: accounts
      MYSQL_DATABASE: account-db
    volumes: 
      - account-data:/var/lib/mysql

  account-service:
    image: com.s63d/er-account-service:1.0.0-3-g85fa8f7
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports: 
      - 8081:8080


  vehicle-db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: accounts
        MYSQL_DATABASE: vehicle-db
      volumes: 
        - vehicle-data:/var/lib/mysql
  vehicle-service:
    image: com.s63d/er-vehicle-service:1.0.0-20-g0731515
    environment: 
      SPRING_PROFILES_ACTIVE: docker-compose
    ports: 
      - 8080:8080
volumes:
  account-data:
  vehicle-data:
    