# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: vehicle-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['vehicle-service:8080']
  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['account-service:8080']
  - job_name: trip-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['trip-service:8080']
  - job_name: trip-consumer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['trip-consumer:8080']
